import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import type { Message } from '../../model/provider.js';

const SECRET_MARKER = /(?:api[_-]?key|token|password|secret|private[_-]?key|authorization|credential)/i;
const PATH_MARKER = /(?:[a-z]:[\\/]|\.\.?[\\/]|\/(?:src|packages|project|workspace)\/)[^\s`'"<>]+/gi;
const ERROR_MARKER = /\b(?:error|failed|failure|exception|erro|falha|stack trace|status\s*[45]\d\d)\b/i;
const queues = new Map<string, Promise<void>>();

function redact(value: string): string {
  return value
    .replace(/(api[_-]?key|token|password|secret|authorization|credential)(\s*[:=]\s*)[^\s,;]+/gi, '$1$2<REDACTED_SECRET>')
    .replace(/\b(?:bearer\s+)[A-Za-z0-9._~+\/-]+/gi, 'Bearer <REDACTED_SECRET>')
    .replace(/\b(?:sk-|sk-ant-|npm_|gh[pousr]_)[A-Za-z0-9._-]{8,}\b/gi, '<REDACTED_SECRET>');
}

async function atomicWrite(file: string, content: string): Promise<void> {
  const previous = queues.get(file) ?? Promise.resolve();
  const next = previous.then(async () => {
    await fs.mkdir(path.dirname(file), { recursive: true });
    const temporary = `${file}.${process.pid}.tmp`;
    await fs.writeFile(temporary, content, 'utf8');
    await fs.rename(temporary, file);
  });
  queues.set(file, next);
  try { await next; } finally {
    if (queues.get(file) === next) queues.delete(file);
  }
}

function safeSessionId(sessionId: string): string {
  return sessionId.replace(/[^a-z0-9._-]+/gi, '_').slice(0, 100) || 'interactive';
}

function normalizeRelativePath(value: string): string {
  return value.replace(/[\\/]+/g, path.sep);
}

export function stateNotesPath(workspace: string, sessionId?: string): string {
  // There is one authoritative state file per workspace. The session id is
  // still included in the document header so recovery can detect a switch.
  // Keeping a stable path is important: compaction must never guess between
  // several session-local notes files.
  void sessionId;
  return path.join(workspace, '.plif', 'NOTES.md');
}

export async function stateNotesHasHardFacts(workspace: string, sessionId?: string): Promise<boolean> {
  const text = await fs.readFile(stateNotesPath(workspace, sessionId), 'utf8').catch(() => '');
  return /## (?:Arquivos tocados|Erros ativos|Fatos que não podem ser perdidos)/i.test(text) && text.trim().length > 80;
}

/** Write a compact, redacted, mechanically-derived state note after a turn. */
export async function writeStateNotes(
  workspace: string,
  sessionId: string,
  messages: readonly Message[],
  turn: number,
  planAnchor?: string,
): Promise<void> {
  const user = [...messages].reverse().find((message) => message.role === 'user')?.content.trim() ?? '';
  const files = [...new Set(messages.flatMap((message) => [...message.content.matchAll(PATH_MARKER)].map((match) => match[0]!)))].slice(-40);
  const errors = messages.flatMap((message) => message.content.split(/\r?\n/).filter((line) => ERROR_MARKER.test(line))).map(redact).slice(-20);
  const pending = messages.flatMap((message) => message.content.split(/\r?\n/).filter((line) => /pending|pendente|next step|pr[oó]ximo passo/i.test(line))).map(redact).slice(-20);
  const decisions = messages.flatMap((message) => message.content.split(/\r?\n/).filter((line) => /decision|decis[aã]o|chosen|escolh/i.test(line))).map(redact).slice(-20);
  if (!user && files.length === 0 && errors.length === 0 && pending.length === 0 && decisions.length === 0) return;
  const lines = [
    `# STATE NOTES — ${safeSessionId(sessionId)}`,
    `<!-- generated by PLIF token-split; last update: turn ${turn} -->`,
    ...(planAnchor ? [planAnchor] : []),
    '## Objetivo',
    user ? redact(user.slice(0, 1000)) : '- null',
    '## Decisões',
    ...(decisions.length ? decisions.map((line) => `- ${line}`) : ['- null']),
    '## Arquivos tocados',
    ...(files.length ? files.map((file) => `- ${file}`) : ['- null']),
    '## Erros ativos (não resolvidos)',
    ...(errors.length ? errors.map((line) => `- ${line}`) : ['- null']),
    '## Pendências / próximo passo',
    ...(pending.length ? pending.map((line) => `- ${line}`) : ['- null']),
    '## Fatos que não podem ser perdidos',
    `- raw transcript remains authoritative; generated notes are a recovery aid (turn ${turn})`,
    '',
  ];
  const file = stateNotesPath(workspace, sessionId);
  const next = lines.join('\n');
  const previous = await fs.readFile(file, 'utf8').catch(() => '');
  if (previous !== next) await atomicWrite(file, next);
}

export interface SpilledToolOutput {
  readonly content: string;
  readonly path: string;
  readonly bytes: number;
  readonly hash: string;
}

export async function spillToolOutput(
  workspace: string,
  sessionId: string,
  callId: string,
  output: string,
  options: { readonly maxInlineChars: number; readonly headChars: number; readonly tailChars: number; readonly dir: string },
): Promise<SpilledToolOutput | null> {
  if (output.length <= options.maxInlineChars || SECRET_MARKER.test(output) || /\[arquivo:|\[result.*spill/i.test(output)) return null;
  const workspaceRoot = path.resolve(workspace);
  // Treat both Windows and POSIX separators consistently. Without this,
  // `..\\outside` is traversal on Windows but a literal filename on Linux.
  if (path.isAbsolute(options.dir) || /^[a-z]:[\\/]/i.test(options.dir) || /^\\\\/.test(options.dir)) return null;
  const spillDir = normalizeRelativePath(options.dir);
  const spillRoot = path.resolve(workspaceRoot, spillDir);
  const insideWorkspace = spillRoot === workspaceRoot || spillRoot.startsWith(`${workspaceRoot}${path.sep}`);
  if (!insideWorkspace) return null;
  const hash = createHash('sha256').update(output).digest('hex').slice(0, 8);
  const relative = path.join(spillDir, safeSessionId(sessionId), `${hash}-${callId.replace(/[^a-z0-9_-]/gi, '').slice(0, 20) || 'result'}.txt`);
  const absolute = path.join(workspace, relative);
  await atomicWrite(absolute, output);
  const omitted = output.length - options.headChars - options.tailChars;
  const marker = `\n… [${omitted} characters omitted — file: ${relative} — sha256:${hash}] …\n`;
  return {
    content: `${output.slice(0, options.headChars)}${marker}${output.slice(-options.tailChars)}`,
    path: relative,
    bytes: Buffer.byteLength(output, 'utf8'),
    hash,
  };
}
