import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

export const TEMP_WORKDIR = '/temp' as const;

export interface SessionTempWorkspace {
  /** Host directory mounted into the agent container at /temp. */
  readonly hostPath: string;
  readonly virtualPath: typeof TEMP_WORKDIR;
  /** Remove only the directory created for this session. Safe to call twice. */
  readonly cleanup: () => Promise<void>;
}

/**
 * Create a disposable scratch directory outside the user's project.
 *
 * The directory name is generated by the operating system, and cleanup never
 * follows a replaced symlink or removes a path outside the system temp root.
 * The virtual path is deliberately stable so prompts and tools do not need to
 * know which host OS is running PLIF.
 */
export async function createSessionTempWorkspace(): Promise<SessionTempWorkspace> {
  const parent = path.resolve(os.tmpdir());
  const parentReal = await fs.realpath(parent);
  const hostPath = await fs.mkdtemp(path.join(parent, 'plif-session-'));
  const createdReal = await fs.realpath(hostPath);
  if (!isInside(createdReal, parentReal)) {
    await fs.rm(hostPath, { recursive: true, force: true });
    throw new Error('PLIF temporary workspace escaped the system temp directory');
  }

  let cleaned = false;
  return {
    hostPath,
    virtualPath: TEMP_WORKDIR,
    cleanup: async () => {
      if (cleaned) return;
      cleaned = true;

      let stat;
      try {
        stat = await fs.lstat(hostPath);
      } catch (error) {
        if (isMissing(error)) return;
        throw error;
      }

      // Never follow a symlink if an external process replaced the session
      // directory before shutdown. Removing the link is the safe operation.
      if (stat.isSymbolicLink()) {
        await fs.unlink(hostPath);
        return;
      }

      const currentReal = await fs.realpath(hostPath);
      if (!isInside(currentReal, parentReal)) {
        throw new Error('refusing to clean a temporary workspace outside the system temp directory');
      }
      await fs.rm(hostPath, { recursive: true, force: true });
    },
  };
}

function isInside(candidate: string, parent: string): boolean {
  const relative = path.relative(parent, candidate);
  return relative !== '' && relative !== '..' && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
}

function isMissing(error: unknown): boolean {
  return Boolean(error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT');
}
